version: '3.2'

services:
  serverless:
    container_name: serverless
    build:
        context: .
        dockerfile: Dockerfile
    working_dir: /workspace
    volumes:
        - ./:/workspace
    environment:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    command: "/bin/bash -c \"source /root/.nvm/nvm.sh; npm install && npm run deploy\""
