Resources:
  S3PublicReadBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: S3BucketMedia
      PolicyDocument:
        Statement:
          - Sid: PublicGetObject
            Effect: Allow
            Principal: "*"
            Action:
              - s3:GetObject
            Resource: arn:aws:s3:::${self:custom.config.image_bucket_name}/*
